eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.146.130:8761/eureka/
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/mysql
    username: root
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8882
